### ISSUE TITLE
Cant update my LCD Display

### ISSUE THREAD

**Issue by pimp1310** [wabbitguy/Kobra_Plus#2]
Hello,
PRINTER : ANYCUBIC kobra plus 

i tried it now for hours, perhaps i make something wrong, first i installed your firmeware everything works well, than i placed the folder DWIN_SET on a empty SD CARD, shut off the printer and put the SD Card in the slot on the display bottom, turned the printer on but nothing happend.

Then i tried it with the files directly on the SD Card without the folder, but same problem, nothing happend.
I formated the SD Card in FAT32 normal with 4096. 

![20230725_113514](https://github.com/wabbitguy/Kobra_Plus/assets/6306057/e531e091-4c8f-4ecf-83df-6782a41f678f)

Have you perhaps a idea  ?

**Comment by wabbitguy** [comment]
@pimp1310 I haven't experienced that myself, but some others have as well. One of users forgot to unzip the DWIN file so that was an easy fix but for the others, it was almost like the display was really fussy about SD cards. 8 and 16GB cards seemed to work the best, the 32GB cards had some problems.

The format is just a good old fashioned FAT32.

Others have power cycled and sometimes, less than 50% of the time, that has worked for them. I find I have to do that with the main firmware occasionally but not the LCD.

The display update doesn't happen all that quick either. It might take 10 seconds for it to figure out there's an update and then start it, from that point it can take another 30 to 50 seconds for it to finish.

About all I can suggest is to try a different SD card. I use the 8GB the Kobra Max came with and so far it's worked for the main firmware and the display updates.

**Comment by pimp1310** [comment]
@wabbitguy 

Thank you for your reply.

I tried it yesterday many Times but get no succes, i tried the original 8gb sd card too, but no luck. 

Is it correct to put only the DWIN_SET folder on the root of the SD card ? 

And it must come a blue flash screen ? 

How do you format your card ? With windows or a tool? For the last tries I used a fat32 formatter tool but still no luck.

**Comment by wabbitguy** [comment]
@pimp1310 I have formatted SDcards both with my Windows emulator and on the Mac with it's Disk Utility app as well. Fat32 for either and the typical 4096 sectors. I normally just use Quick Format, not the bit level one. I normally use the 8GB card, or a couple of LEXAR 16GB cards.

The SDcard is empty and the only folder on it is the:

DWIN_SET

Inside the folder will be four files:

22_Config.bin
16_68_.icl
14ShowFile.bin
13TouchFile.bin

I know that some users in the Facebook forums have reported that the card reader in the LCD refuses to work and they opened a repair ticket with Anycubic, get it replaced and it works after that. I also know more than a couple end users that have dead USB ports on their motherboard in the main printer. So quality control appears to be hit and miss.

**Comment by pimp1310** [comment]
@wabbitguy 

i get from the support of anycubic a zip file for flashing the lcd, there is the name of the file another as yours, is this a problem?


![ubennant](https://github.com/wabbitguy/Kobra_Plus/assets/6306057/277b97be-d93e-4480-8be9-1b7c27bf4791)


in the folder are many .bmp files and this 

DWINOS.bin
T5L_OS_DGUS2_V10.BIN
T5LCFG.CFG
22_Config.bin
23_═╝▒Û.icl
24_╦╬╠Õ14X14.DZK
14ShowFile.bin
16_68%.icl
0_DWIN_ASC.HZK
13TouchFile.bin

**Comment by wabbitguy** [comment]
@pimp1310 those are not only the display and configuration files, those are firmware files as well. 3rd party developers have no access to the firmware on those units at all so our files are the 4 which are the screen locations, compressed BMP's, touch settings, etc.

Just for the heck of it I'd try flashing that firmware and see if it works. If that does, then try the DWIN_SET you got from 1.8.3. I know there was an update for the firmware twice last year for the motherboard firmware, and it seemed to me there might have been one for the LCD late last fall (now that I'm looking through my notes)...

All those BMP files are ignored for our screen updates, Anycubic published them so we could modify the colours and add text areas if we wanted to. But we can't change how the display works.

I just downloaded the DWIN_SET.zip and put it on a card, showed up the LCD right away, but since there was no changes it didn't update the display.

**Comment by pimp1310** [comment]
@wabbitguy 

i tested the original FW and nothing happend, no Blue flash screen, or motherboard beeping how in the guide from anycubic stands.

**Comment by wabbitguy** [comment]
@pimp1310 you don't get any beeps when you do the LCD updates. It just shows a file listing on a blue background and it works its way down the list. The big compressed BMP file is the one that takes the longest to process.

And those all have to be in a DWIN_SET folder or the LCD will ignore them entirely. I put the DWIN_SET.zip file here from the last update AnyCubic did for the Kobra Max (2.8.7). You can try it.

[DWIN_SET.zip](https://github.com/wabbitguy/Kobra_Plus/files/12168073/DWIN_SET.zip)

**Comment by pimp1310** [comment]
@wabbitguy 

i tested it, and nothing happens

**Comment by pimp1310** [comment]
@wabbitguy 

I don't remember exactly which firmware version of anycubic I had on it when I installed your marlin, is that important because of the display problem?

should I try to install the last original firmware first and then yours again? or does that have nothing to do with it?

**Comment by wabbitguy** [comment]
@pimp1310 2.8.7 firmware was the last one for the Kobra Max AnyCubic did last year. It shouldn't matter for the display since the display talks to the motherboard using 1960's serial protocols. I put the 2.8.7 firmware here for you if you want to try it on the motherboard. Keep in mind switching firmware from theirs to what I've done requires re-levelling if you're going to do any printing. Anycubic uses a 5 x 5 grid, I use a 7 x 7 for bed mesh.

The DWIN_SET just changes the colour of the display (monochrome is boring LOL) and adds the feature it can display M117 GCODE (messages from a host for example; aka Octoprint/Repetier Server Pro/AstroPrint) and your printer stats. Printer stats can be obtained via USB with Pronterface and an M78 GCODE so having them on the display is just more handy.

Thus you don't "really" need the LCD update, it's just slightly more of a visual aspect than something you absolutely have to do.

[firmware.bin.zip](https://github.com/wabbitguy/Kobra_Plus/files/12175598/firmware.bin.zip)

**Comment by wabbitguy** [comment]
@pimp1310 Anycubic apparently also ran out of motherboards used in the original Max's. At this point I don't know if the currently shipping Max's use the same motherboard as the original, or they are using a different board. Anycubic doesn't exactly keep us up to speed with what they are doing.

I do know that some original motherboards have burned out and the replacement boards Anycubic provided are different. I was told by one person that the new motherboard also was supplied with different firmware but I haven't been able to get 100% verification of that either. None the less the LCD display is the same. Hasn't changed a bit.

**Comment by pimp1310** [comment]
> 

@wabbitguy 

I have the PLUS Not the MAX kobra, or is it the same firmeware ?

**Comment by wabbitguy** [comment]
@pimp1310 whoops...I'd completely missed the PLUS firmware. Sheesh. Talk about a senior moment. Ugh...sorry...very sorry... so used to dealing with Max's...sigh...

Toss that last firmware and firmware zip. This is the last known update for the PLUS. 2.8.6. I included it here.

Ultimately the difference between the two is the bed/height dimensions set in slicer. Firmware wise they use the same motherboard and so on. So are they swappable? I dunno. I'll go with no just to be on the safe side.

[firmware.bin.zip](https://github.com/wabbitguy/Kobra_Plus/files/12176262/firmware.bin.zip)

**Comment by pimp1310** [comment]
@wabbitguy 

Okay no problem :-) 
The dwin_set folder you posted above is for the kobra plus or max? Or is the display the same ?


Do you think it helps to go back to the 2.8.6 from anycubic and than reflash you marlin version helps me with the display problem ?

**Comment by wabbitguy** [comment]
@pimp1310 displays are identical. The DWIN folder set is identical for both printers. Flashing the motherboard isn't going to cure the LCD. They are two completely independent systems. If the LCD won't accept the DWIN set I'd say it's the SDcard slot in the display that isn't working.

**Comment by pimp1310** [comment]
@wabbitguy 

Okay I contacted the anycubic Support and I get a New display.
When the new display arrives I would update the issue here if it's okay?

Thank you for your time and help.

**Comment by wabbitguy** [comment]
@pimp1310 that would be helpful. Thanks.

**Comment by wabbitguy** [comment]
@pimp1310 I have been appraised today that Anycubic is now using different displays in both their newer printers AND as replacement parts for their older printers. The original displays used a DWIN_SET to update the displays, the new displays use a .tft file to do the same thing.

The issue is Anycubic has not told any of us about the change, nor have they provided the screen source to work with. Thus this could be exactly why your display refuses to update. If they send you a new display, do me a huge favour and snap some photos of it for me. That way we'd know for sure.

Sorry about this, I just found out about it today.

Mel

**Comment by pimp1310** [comment]
@wabbitguy  only from the New one ? Or from the Old where the flashing doesn't work too? The old one is still here.

**Comment by pimp1310** [comment]
![20230729_130827](https://github.com/wabbitguy/Kobra_Plus/assets/6306057/6f26d046-48a6-46b6-872a-547a77207beb)
![20230729_130831](https://github.com/wabbitguy/Kobra_Plus/assets/6306057/16247ef7-ffaf-488a-a2c7-19382c392b05)
![20230729_130651](https://github.com/wabbitguy/Kobra_Plus/assets/6306057/2ae4014c-ffd3-4c65-91f6-fe66d7a5f820)

**Comment by wabbitguy** [comment]
@pimp1310 ah HA! THANK YOU FOR THE PIX!

The original production run of Anycubic printers with the same looking display used Nextion LCD panels. They are a more common and expensive panel. My guess is Anycubic had a bunch of them made and when they ran out of stock they went to a company who is associated with Nextion but typically only produces LCD's for the Asian market itself (consider them a clone of a Nextion).

The company that makes those TJC LCD's is TAOJINGCHI and a strictly Chinese company and web site. [here](https://www.tjc1688.com)

They use a completely different software system to build for their panels, and as far as I can find there's no English version of it. So no idea what its requirements are or anything else about building working data for it.

Thus at present there is no way to change what that LCD does or how it operates. Sorry about that news. But again, thank you so much for the pix! Without that I'd have still been guessing.

Mel

**Comment by nikjust** [comment]
did you tried to send HMI/TFT nextion file to UNUF discord?

**Comment by wabbitguy** [comment]
@nikjust never used Discord so I have zero knowledge of it, nor any of the groups on there. Also since I have no TJC panel to test with.

For the Nextion/DWIN display there is no HMI or TFT file. There's an ICL file that is the main graphic payload and 3 other files for the configuration support. I suspect the TJC panels take the BMP's and configuration files and lump them into a single TFT file for their panels.

I'm sure someone will figure it all out eventually, it just won't be me. In addition Anycubic now uses a completely different motherboard Tri-Gorilla-ProB_V1.0.2 in new production runs and as replacements. It has specific firmware for and they have not released the source code they are using for the new board.

**Comment by pimp1310** [comment]
@wabbitguy 

Gives a way to contact you ? Perhaps a messenger?

I have a question or two, I have problems with the display cable pins of my printer perhaps you have a idea

**Comment by wabbitguy** [comment]
@pimp1310 I don't use messengers, other than the Facebook one every once in a blue moon. Anything that gets posted here I get an email notice from when I am in the shop. But I'm also retired so working is more of a pastime than anything else...LOL

So I'm not around all the time, mostly about 4 or 5 times a day at most, time zone here is Pacific Standard Time.

As for the display cable pins, last time I looked at those there was 4 wires in some Dupont connectors in a JST housing. Pretty brain dead stuff since it's Vcc, GND, RX, TX lines.

Mel
---

**Comment by pimp1310** [comment]
Yes correct 

Vcc,gnd,rx,TX I tried to connect to the display cable a bltouch for my printer and the pins names are 

According to marlin from anycubic for this board

#define BOARD_USART4_TX_PIN     PB10    // LCD
#define BOARD_USART4_RX_PIN     PH2

But I can try what I want I can't get the bltouch to work the pin down or up command doesn't work.
The little blue led blinks on the bltouch but the pin doesn't move.

Have you perhaps a idea ?

**Comment by wabbitguy** [comment]
@pimp1310 easy question. The BLTouch requires the "servo" libraries in the firmware. AnyCubic left in the filenames to allow compilation but completely removed all the code in the both the .h .cpp files so no servo control happens.

The BLTouch also has to be enabled in the configuration file and since it also requires the servo libraries to move the pin it's not going to work. Already tried to help a couple of people to get a BLTouch to work. When we added the proper libraries it generated a LOT of compile errors because of the way Anycubic coded Marlin. So after 40 hrs we simply gave up.

Now you know....Anycubic writes terrible firmware.

Mel
---

**Comment by pimp1310** [comment]
@wabbitguy 
Hi

Thanks for the detailed answer, but I forgot to mention that I'm currently using klipper and that should be supported normally if you specify the pins, at least that's how I understood it.

But no matter what combination of the two pins I try, the bl Touch just doesn't move in or out.

It flashes blue on command but that's it.

I tried to look for help in the klipper discord but apparently it's a hardware problem so I wanted to ask you if these are the right pins for the kobra plus

**Comment by wabbitguy** [comment]
@pimp1310 I don't use Klipper, nor have any interest even remotely in it. I'm a Marlin guy, far easier for me to modify and control than use Klipper. While I found Klipper did print faster, and that worked great for prototyping, for structural parts that I print it also made for lousy layer adhesion.

It's probably matured since I tried it but at the time it seemed more like a sales pitch to sell a Raspberry PI and get saddled with Octoprint or Fluidd/Mainsail than anything else to me...LOL

Anycubic has two motherboards they now use. A ProA and a ProB. Is there a difference between the two? Probably. Maybe. Who knows. There's no schematic for them so unless someone takes the time to pin them out...unknown.

So the result is you tried two pins, neither work. So the next question would be has anyone with PLUS managed to get a BLTouch to work on the PLUS. If they did, what pins, what motherboard, what configuration file. If no one has been able, that'd be a pretty good indicator that it's not going to work with the current motherboard. Which could be due to a motherboard issue or a Klipper configuration/firmware issue.

Myself, I'd be inclined to use a Triangle Labs nozzle probe and trigger board. Level the thing once, be done with it. And I have a BLTouch but it's in my junk box. Easier with the nozzle probe and less hassle.

Good luck with Klipper, hope you get it figured out.

Mel

**Comment by TTVert** [comment]
Hey if you need the tft file for this printer I had to pull teeth at AC to get it as even they didn't seem to know they were shipping with TJC screens now.  They eventually sent me a tft after i guaranteed them 10 times w/ pics, model #s, etc. that it wasn't a DWIN but alas it was an older tft.  After much research, here is the latest.  Just unzip into root of SD card, doesn't even need to be in a TJC_SET folder or an empty SD card from what I recall.

[Anycubic_20230529T_newui.zip](https://github.com/wabbitguy/Kobra_Plus/files/12282485/Anycubic_20230529T_newui.zip)

**Comment by wabbitguy** [comment]
@TTVert thanks for the tft.

It's like the DWIN set where the editor software creates a file to place on the SD card based on all the other files needed (like the BMP's and configuration matrix). So somewhere there's some editor (my understanding is that it's in Chinese with an English sub available), and it needs to be set up somehow (no clue on thats done) and then it creates the TFT file for the display. Much the same as the DWIN set is created.

In order to create the TFT, it has to have all the other files in their respective areas/directories/folders/earthly planets so the editor can read them and create the TFT file. Anycubic needs to supply that setup or we'd have to reverse engineer it. And for me, that'd require more time than the Kobra is worth. I could probably swap  out any motherboard I have in stock with an ancient LCD2004 and be further ahead with more features in less time...ROFLOL...

All these touch screens are pretty. I want functional. They don't qualify. Maybe some day...I'm a fussy ole coot...

Mel

**Comment by pimp1310** [comment]
@wabbitguy 

Iam here again, for me klipper don't work, too much, I now know I only want to print, and your marlin worked great.

But I resoldered  the resistor 65 to 66 on the board to get klipper to work. I think I can't flash your firmeware again before I change the resistor (bridge) back ?

And gives something like "klipperscreen" for marlin and a android tablet ? 

Thank you

**Comment by wabbitguy** [comment]
@pimp1310 the resistor changes how the Marlin firmware talks to the steppers for stuff. I found what needs to be changed for the firmware once the resistor mod has been done. If you want I can compile up a specific version for you with the fixes. Let me know if you want that.

As for Klipper, I was done that road already myself, before the Kobra Max ever showed up here. I found it's like everything else, it has some pros and cons. The cons for me simply out weighed the pros so, back to good old fashion Marlin for me.

Mel

**Comment by pimp1310** [comment]
@wabbitguy  

That would be amazing when you do this 😍. 
Yeah perhaps I'm to old with my 38 years and a little baby. I have no time for playing around I want still print 😃

**Comment by wabbitguy** [comment]
@pimp1310 As requested. Compiled for a Kobra Plus. Adjusted for resistor fix. Custom machine name.

A baby at 38...when I was 38 we had two kids, one was 20, the other was 17. Let you do that math on that one... but I'm retired now, same kids and wife (married 53 years). Now I write software cause it keeps my mind active and I've always enjoyed doing it. I play golf to keep my "assets" from spreading too much..LOL

[firmware.bin.zip](https://github.com/wabbitguy/Kobra_Plus/files/12330026/firmware.bin.zip)

**Comment by pimp1310** [comment]
@wabbitguy 

Thank you very much you rescued my printer:-)
Perhaps you have a idea I try to control my y axis and how tightend it must be, gives there a documentation. ?

Yeah one kid is more as enough for me, I miss my sleep time so much after the work

**Comment by wabbitguy** [comment]
@pimp1310 no worries, happy to help out.

Printers are wonderful when they work and the most annoying things on the planet when they don't. I've parted out so many that have gotten to that point I've lost count. Reminds me of trying to fix a car that turns into a money pit. :-)

For the Y axis, I think there was someone who came up with a gauge or something to help out. I know mine are not what I'd call "singing tight", but merely snug. There's guys who claim they have it "tuned" to low E on a bass guitar but that seems a little overkill to me. I snug them up, hold the stepper so it can't turn, grab the bed and see if I can move it to make the belts slip. If I can, I snug a little more. If not, well, if I can't cause a slip, I doubt the stepper motor will either.

What I have found on some Max's (mine included), is when the speed/jerk/accel get too high it over heats the stepper driver on the motherboard. When that happens, I get a loud "clunk" and a Y axis shift. For me, if I keep the print speeds around 60mm/s I'm fine, I get up into the 80mm/s range and it's "clunk" city.

The PLUS's have a smaller bed so not as much weight to throw around but perhaps the cooling for the motherboard could be better, or perhaps they suffer the same speed cap as the Max does.

Mel

**Comment by pimp1310** [comment]
@wabbitguy 

Now I found the time and installed your version. Perfect thanks but I have a problem perhaps you have a idea the this should be circle and no its not :-)

![20230831_190215](https://github.com/wabbitguy/Kobra_Plus/assets/6306057/fcc09838-ff37-4c03-91cd-d949247d5a7f)


It's printed with 52 speed and 1000 max acceleration

**Comment by wabbitguy** [comment]
@pimp1310 got that it's not a circle, I assume all that extra around it for adhesion to the bed? Dunno, never used brims, skirts or rafts on any of my printers.

Any way, is that brim/skirt/raft round?

If it's round, then at least you'd know the printer can do a round object. At the first layer speed. If the diameter of that taller "circle" is like <30mm, it looks too fast to start with because I can see the lamination lines are visible between the inner and outer layers. Thats usually too fast, under extrusion (a lot of times because of speed), or too much fan causing some shrinkage from fast cooling. Plus if the travel moves force the nozzle to jump across the circle for each newer layer, the nozzle could be lacking on filament and you get less extrusion which would look like an oval but if you use a caliper and measure wall thickness you might find it's thinner at the "oval" side.

If the brim/skirt/raft is NOT round, then you need to determine the direction where it is not round. I.e. oval in the Y or X axis. Once that is deduced, then you need to look at the belts/gears (gear grub screws in particular) make sure all is reasonably snug. Start with all print speeds set to the same speed (like 30mm/s). Travel speed should be something like 120mm/s. Do the circle test and see what it looks like. If that turns out fine, ramp all the speeds up to 40mm/s. Same test. Compare. Repeat with 50mm/s. At some point you could find that it just starts to fail. At that point you know the speed cap.

Mel

**Comment by pimp1310** [comment]
yeah thats brim.

yeah its getting better, for me understanding has my kobra Plus a "EPCOS 100K B57560G104F" Extruder or a "ATC Semitec 104GT-2" ?

**Comment by wabbitguy** [comment]
@pimp1310 In all the hot ends I've been able to see and test out (with the help of a lot of others) it's neither of those. For the temp range the closest we've found that matches the knock-off thermistor Anycubic uses is a:

100k beta 3950 1% thermistor (Used in Keenovo AC silicone mats and most Wanhao i3 machines) (4.7k pullup)

It's similar to the Semitec 104GT-2 but the PID range doesn't react the same. We found that when we'd set the temp to 200C and then measure the actual outside heater block temp we'd get 200C. Of course that's completely impossible because the heater is internal to the block and the outside edges of the block will always be 10-15C less.

When we found that it explained why with the stock firmware we could print PLA at 180-185C with no problem at all. When in actuality it shouldn't have worked hardly at all. We then went through and tested the settings, ran more test prints than I can ever remember doing, and finding the 100k beta (#11) was the most accurate.

Since then a lot of us who did the tests have ordered new hot ends from Anycubic and found nothing has changed. They are still using some goofy thermistor that still matches our new setting.

None of us has ordered after market or 3rd party hot ends from say, Aliexpress. For those there may a change required but again, it would take some testing and a good meter for testing that heater block temp (we used Fluke meters and trapped the probe between the heater block and the silicone sock).

Mel
