### ISSUE TITLE
Anycubic kobra plus 

### ISSUE THREAD

**Issue by Clayswinton** [wabbitguy/Kobra_Plus#4]
Hi I uesd your firmware and give but my printer is stuck on the Logo screen what can I do to get it working again 
Is the motherboard dead? 
Any help much appreciated

**Comment by wabbitguy** [comment]
@Clayswinton it's nearly impossible to destroy a motherboard with any firmware update so that shouldn't be an issue.

Anycubic now uses two different motherboards for the Kobra series. If you check the photos of the motherboards you'll see the difference is the USB style connector. The original uses the older USB Host 2.0 connector (big square one). The new one uses one of the more modern micro USB connectors.

If you have the original motherboard, I'd suggest simply flashing it again with the new firmware. You should hear the 5 beeps and the display should then switch to the normal main page. In a few cases the display doesn't change but simply removing the SDCARD from the printer and power down, wait 5 seconds, power up will result in the printer's normal startup sound and main page display.

Should that fail, your only option is to revert to factory firmware. That can be found on AnyCubic's web site (look for V2.8.6; again for the original motherboard only):

[Anycubic Firmware Page](https://www.anycubic.com/pages/firmware-software)

Mel

**Comment by Clayswinton** [comment]
Thanks for you response but after much perseverance I finally got it
working and it fixe so many problems I was having with this machine thanks
for all your help
Love your work

Regards
Clayton Swinton

**Comment by wabbitguy** [comment]
@Clayswinton thanks very much for the compliment!

Very much appreciated and I'm so glad you got it sorted out and working!

Mel
