### ISSUE TITLE
PrusaSlicer Profiles for this FW

### ISSUE THREAD

**Issue by sandmix** [wabbitguy/Kobra_Plus#8]
Hi, I wouyld like to ask if you can possible share working PrusaSlicer profiles for this FW I used some of your Max profiles they seem to be workin good, was interested maybe you have profile for 0.15 ? Thanks

**Comment by wabbitguy** [comment]
@xromansx sorry I don't have any profiles at all for the PLUS, the users with the PLUS have used the Max profiles and just changed the bed size and graphic.

As for the 0.15 when you're looking for the best layer height make sure the height is divisible by .04 so that you get the best calculations from slicer. So you'd be simply changing the 0.2mm layer height in the Max profile to 0.16 or 0.12. Start with a 0.2 layer height for the first layer to compensate for any bed level issues.

**Comment by sandmix** [comment]
Thank you, it's really usefull info.
