### ISSUE TITLE
Kobra 2 Plus

### ISSUE THREAD

**Issue by Fajka0** [wabbitguy/Kobra_Plus#9]
Hello, could this update be extended to Kobra 2 Plus? 
Or is it also good for Kobra 2 Plus?
For me, the most important thing is 100C bed temp.

**Comment by wabbitguy** [comment]
@Fajka0 The Kobra 2 PLUS runs a more or less custom version of Klipper, whereas the firmware for the original Kobra Plus runs Marlin and uses a different display and motherboard setup. The two, to my knowledge aren't interchangeable.

Anycubic limited the temp on the 2 PLUS to 105C (but they subtract 15C from the max allowed if I remember correctly) so that's why it's set to 90C.

I don't see any way around that limitation other than trying to hack into their closed off Klipper install. There's a bunch on Reddit trying to do that:

[Kobra 2/Plus/Pro/Max Klipper](https://klipper.discourse.group/t/printer-cfg-for-anycubic-kobra-2-plus-pro-max/11658/157)

Mel
